Add sample to refresh and tsv scripts DAP
DataBiosphere/dog-aging-ingest pull request #167
Opened 2021-06-09 14:50 UTC by eparkmonster

## Why
Sample extraction and transformation pipeline have been merged. We need to add sample to the refresh and tsv scripts

## This PR
Adds sample to manual refresh and convert TSV script

2021-06-09 15:35 UTC, aherbst-broad requested changes
I think we should stop updating the manual refresh script (in fact we should remove it). Instead all refresh should go through the dagster pipeline.

2021-06-09 15:35 UTC, aherbst-broad commented on hack/manual_refresh.sh
> +if [ "$(pipeline_requested sample)" -eq 1 ]; then
🔧 Let's remove this script altogether, we should not be using it anymore.

2021-06-10 13:15 UTC, quazi-broad approved these changes
lgtm

2021-06-10 13:18 UTC, aherbst-broad approved these changes

2021-06-10 13:39 UTC, merged