Mapping CSV Tool and EOLS General Transformations Code
DataBiosphere/dog-aging-ingest pull request #171
Opened 2021-06-14 21:45 UTC by quazi-broad

## Why

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1808)

## This PR
Added a mapping transformation script to process schema csvs to json schemas and fragments
Added EOLS Fragments and general conditions to the dog aging schema.
Added EOLS pipeline, pipeline builder, transformation code, and unit tests for general conditions.

2021-06-14 21:45 UTC, quazi-broad commented
Realized that the RedCap data dict has some gating logic for some of those fields, added notes on what needs to be refactored.

2021-06-15 13:03 UTC, aherbst-broad requested changes
Looking good, a couple of points that could use cleanup in the schema generation script.

2021-06-15 13:03 UTC, aherbst-broad commented on scripts/convert_mapping_to_schema.py
> +    general_fragment = fragments.pop(TDR_FRAGMENT_GENERAL)
🔧 I think this should handle the edge case where there is no general fragment ( i.e., everything is bucketed) with a default empty dict:

```suggestion
    general_fragment = fragments.pop(TDR_FRAGMENT_GENERAL, {})
```

2021-06-15 13:03 UTC, aherbst-broad commented on scripts/convert_mapping_to_schema.py
> +        print(os.getcwd())
⛏️ Unless this debug output is really needed remove it.

2021-06-15 13:03 UTC, aherbst-broad commented on scripts/convert_mapping_to_schema.py
> +        with open(f"schema/{table_name}_{fragment}.fragment.json", "w") as f:
🔧 We should parameterize the output path (ie consume via a cli arg and thread through)

2021-06-15 13:03 UTC, aherbst-broad commented on scripts/convert_mapping_to_schema.py
> +    with open(f"schema/{table_name}.table.json", "w") as f:
🔧 Same comment about parameterizing the output path.

2021-06-15 13:03 UTC, aherbst-broad commented on scripts/convert_mapping_to_schema.py
> +def run(table_name: str, mapping_csv: str) -> None:
⛏️ This could use a more descriptive name. Perhaps `render_jade_table_schemas`?

2021-06-16 12:50 UTC, aherbst-broad approved these changes
lgtm

2021-06-16 13:51 UTC, raaidbroad approved these changes

2021-06-16 21:45 UTC, quazi-broad commented on dap-etl/transformation/src/main/scala/org/broadinstitute/monster/dap/eols/EolsTransformationPipelineBuilder.scala
> +    rawRecords
Added a new ticket to address this: [DSPDC-1817](https://broadinstitute.atlassian.net/browse/DSPDC-1817)

2021-06-17 13:32 UTC, merged